name: Windows

on:
   pull_request:
   workflow_dispatch:

jobs:
  qt:
    name: Windows Build
    runs-on: windows-latest

    steps:
      - name: Cache Qt
        uses: actions/cache@v3  # not v2!
        with:
          path: ../Qt/6.5.3
          key: ${{ runner.os }}-QtCache-Qt6-2
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.*'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          install-deps: 'true'
          cached: 'true'
          setup-python: 'true'
          modules: 'qtpositioning qtwebchannel qtwebengine qtwebsockets qtwebview debug_info qt5compat qtshadertools qtwaylandcompositor'
          tools: 'tools_qtcreator,qt.tools.qtcreator tools_ninja tools_cmake'
          set-env: 'true'
          
      - name: Installing Conan
        run: |
          pip install wheel setuptools
          pip install conan --upgrade
          conan --version
      - name: Configuring Conan Profile
        run: |
          conan profile detect --name default
          conan profile show
      - uses: actions/checkout@v2
      - name: Configure
        run: |
          git submodule update --init
          cmake -S . -B jasp_build -DGITHUB_PAT=${{ secrets.GPAT_FOR_JASP }} -DGITHUB_BUILD=ON -DJASP_TEST_BUILD=ON
      - name: Building JASP
        run: cmake --build jasp_build
